networks:
  confluence-network:
    driver: bridge

volumes:
  confluence-data:
  confluence-postgres:

services:
  postgres:
    image: postgres:15
    volumes:
      - confluence-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: confluence
      POSTGRES_USER: confluence
      POSTGRES_PASSWORD: confluence
    networks:
      - confluence-network
    hostname: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "confluence", "-U", "confluence" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  confluence:
    image: atlassian/confluence:8.6
    volumes:
      - confluence-data:/var/atlassian/application-data/confluence
      - ./data:/data
    environment:
      JVM_MINIMUM_MEMORY: 2g
      JVM_MAXIMUM_MEMORY: 4g
      JDBC_DRIVER: org.postgresql.Driver
      JDBC_USER: confluence
      JDBC_PASSWORD: confluence
      JDBC_URL: jdbc:postgresql://postgres:5432/confluence
    ports:
      - '8090:8090'
    networks:
      - confluence-network
    hostname: confluence
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      data-loader:
        condition: service_completed_successfully
    command: /data/entrypoint.sh

  data-loader:
    image: postgres:15
    volumes:
      - ./data:/data
    networks:
      - confluence-network
    environment:
      PGDATABASE: confluence
      PGUSER: confluence
      PGPASSWORD: confluence
      PGHOST: postgres
    command: sh ./data/load.sh
    depends_on:
      postgres:
        condition: service_healthy
