name: ci
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      # Add any environment variables needed to run baton-confluence-datacenter
      BATON_HOSTNAME: 'http://localhost:8090'
      BATON_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # The following parameters are passed to grant/revoke commands
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Run Docker Compose as a Daemon (to start postgres and confluence)
        run: docker compose -f ./docker-compose.yml up --detach
      - name: Build baton-confluence-datacenter
        run: go build ./cmd/baton-confluence-datacenter
      - name: Run baton-confluence-datacenter
        run: ./baton-confluence-datacenter
      - name: Install baton
        run: ./scripts/get-baton.sh && mv baton /usr/local/bin
      - name: List Grants
        run: baton grants
      - name: Test granting/revoking
        env:
          BATON: 'baton'
          BATON_CONFLUENCE_DATACENTER: './baton-confluence-datacenter'
          BATON_GRANT: 'space:TEST:delete-page:user:4028408390705fdc01907061af0d0000'
          BATON_ENTITLEMENT: 'space:TEST:delete-page'
          BATON_PRINCIPAL: '4028408390705fdc01907061af0d0000'
          BATON_PRINCIPAL_TYPE: 'user'
        run: ./scripts/grant-revoke.sh
